config/routes.rb
Rails.application.routes.draw do
  
  post 'order_items/create', to:'order_items#create', as: 'order_items'
  # Orders
  resources :orders, only: [:create, :show, :new, :update] do
    get '/payment', to: 'charges#new', as: 'new_charge'
    resources :charges, only: [:create]
    resources :reviews, only: [:new, :create]
  end
  devise_for :users

  # Landing s and dashboards
  root 'landing#index', as: 'home'
  get '/shopdashboard', to: 'seller_profiles#index', as: 'seller_profile'
  get '/dashboard/', to: 'dashboard#index', as: 'dashboard' 
  
  # Routes for profile
  post '/profiles', to: 'profiles#create', as: 'profiles'
  get '/profile/new', to: 'profiles#new', as: 'new_profile'
  get '/profile/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profile', to: 'profiles#update'
  put '/profile', to: 'profiles#update'
  # resources :profiles, only: [:new, :edit, :create, :update]
  
  # Routes for seller profile
  
  # Routes for shop
  resources :shops do
    get '/reviews', to: 'reviews#index', as: 'reviews'
    get '/orders', to: 'orders#index', as: 'orders'
  end
  # Routes for items
  resources :items, only: [:new, :create, :update, :edit, :destroy] 
  
  # Routes for conversations
  resources :conversations do
    resources :messages
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @orders = Order.where(buyer: current_user)
    @profile = current_user.profile
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container bg-blue text-center">
  <h1 class="heading-font txt-white py-3">My Dashboard</h1>
  <span class="col-12 col-lg-12">
    <h5 class="heading-font txt-grey pb-3"><%= "#{@profile.first_name}, #{@profile.email}" %></h5>
  </span>
  <span class="col-12 col-lg-12">
    <%= link_to edit_profile_path, class: "btn btn-red mb-4" do %>
      <%= fa_icon "pencil", text: "Edit My Details" %>
    <% end %>
    <% if current_user.shop.nil? %>
      <%= link_to new_shop_path, class: "btn btn-red mb-4" do %>
        <%= fa_icon "shopping-bag", text: "Start a shop" %>
      <% end %>
    <% else %>
      <%= link_to @shop, class: "btn btn-red mb-4" do %>
        <%= fa_icon "shopping-bag", text: "My Shop" %>
      <% end %>
    <% end %>
  </span>
</div>

<div class="row">
  <div class="col-12 col-lg-12 mb-3">
    <div class="container bg-grey text-center">
      <h4 class="heading-font txt-black py-4">My Purchases</h4>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Items</th>
          <th>Delivery</th>
          <th>Price</th>
          <th>Order</th>
          <th>Leave Review</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td>
              <%= order.date %><br>
              <%= order.time %>
            </td>
            <td>
              <% order.order_items.each do |order_item| %>
                <%= order_item.quantity %> x <%= order_item.name %><br>
              <% end %>
            </td>
            <td>
              <%= order.delivery_address %>
              <%= "from #{order.shop.street_address}, #{order.shop.suburb}, #{order.shop.state} " if order.delivery.nil? %>
            </td>
            <td>$<%= order.subtotal %>0</td>
            <td>
              <%= link_to order_path(order), class: "btn btn-red" do %>
                <%= fa_icon "file-text-o" %>
              <% end %>
            </td>
            <td>
              <% if order.review %>
                <div class="btn btn-primary">
                  <%= fa_icon "check-square", text: "Reviewed" %>
                </div>
              <% else %>
                <%= link_to new_order_review_path(order), class: "btn btn-red" do %>
                  <%= fa_icon "square" %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="container bg-grey text-center py-3">
      <%= link_to "View All", orders_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>