config/routes.rb
Rails.application.routes.draw do
  
  post 'order_items/create', to:'order_items#create', as: 'order_items'
  # Orders
  resources :orders, only: [:create, :show, :new, :update] do
    get '/payment', to: 'charges#new', as: 'new_charge'
    resources :charges, only: [:create]
    resources :reviews, only: [:new, :create]
  end
  devise_for :users

  # Landing s and dashboards
  root 'landing#index', as: 'home'
  get '/shopdashboard', to: 'seller_profiles#index', as: 'seller_profile'
  get '/dashboard/', to: 'dashboard#index', as: 'dashboard' 
  
  # Routes for profile
  post '/profiles', to: 'profiles#create', as: 'profiles'
  get '/profile/new', to: 'profiles#new', as: 'new_profile'
  get '/profile/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profile', to: 'profiles#update'
  put '/profile', to: 'profiles#update'
  # resources :profiles, only: [:new, :edit, :create, :update]
  
  # Routes for seller profile
  
  # Routes for shop
  resources :shops do
    get '/reviews', to: 'reviews#index', as: 'reviews'
    get '/orders', to: 'orders#index', as: 'orders'
  end
  # Routes for items
  resources :items, only: [:new, :create, :update, :edit, :destroy] 
  
  # Routes for conversations
  resources :conversations do
    resources :messages
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  include ShopPhotoUploader[:shop_photo]
  include UserPhotoUploader[:user_photo]
  belongs_to :user
  has_many :item
  validates_presence_of :shop_name, :cuisine_type
  validates :delivery_cost, numericality: { greater_than_or_equal_to: 0, less_than: 20 }
  
  CUISINE_TYPES = ["Continental", "Chinese", "French", "Italian", "Japanese", "Mexican", "Spanish", "Ethiopian", "Thai", "African", "Vietnamese"]
  FILTERS = [nil, "Distance", "Review Score", "Popularity"]

  # Method to see only shops with active items
  def self.active_items
    shop_id = []
    Item.where(active: true).each do |item|
      shop_id << item.shop_id
    end
    self.where(id: shop_id)
  end

  # Method to search term
  def self.search (term)
    items = Item.where('lower(name) Like ? OR lower(description) Like ?', "%#{term.downcase}%", "%#{term.downcase}%").where(active: true)
    shop_id = []
    items.each do |item|
      shop_id << item.shop_id
    end
    self_search = self.active_items.where('lower(shop_name) Like ? OR lower(cuisine_type) Like ?', "%#{term.downcase}%", "%#{term.downcase}%")

    (self.where(id: shop_id) + self_search).uniq
  end

  # Start address methods
  def street_address
    User.find(self.user_id).profile.street_address
  end

  def suburb
    User.find(self.user_id).profile.suburb
  end

  def state
    User.find(self.user_id).profile.state
  end
  # End address methods

  def owner
    User.find(self.user_id)
  end

  def average_score
    average =  Review.where(shop: self).average(:score)
    '%.1f' % average if average
  end

  def reviews
    Review.where(shop: self)
  end

  def longitude
    User.find(user_id).profile.longitude
  end
  
  def latitude
    User.find(user_id).profile.latitude
  end

  def distance_from_user (user)
    Geocoder::Calculations.distance_between([self.longitude,self.latitude], [user.profile.longitude,user.profile.latitude], :units => :km).round(1)
  end
  
  def popularity
    Order.where(shop: self).count + Review.where(shop: self).count
  end

  def self.filter_by(word, user)
    if word == "Distance"
      filtered = self.active_items.sort_by {|shop| shop.distance_from_user(user) }
    elsif word == "Review Score"
      filtered = self.active_items.sort_by {|shop| shop.average_score.to_i }.reverse
    elsif word == "Popularity"
      filtered = self.active_items.sort_by {|shop| shop.popularity }.reverse
    end
    filtered
  end

  def self.filter_search_by(term, word, user)
    if word == "Distance"
      filtered = self.search(term).sort_by {|shop| shop.distance_from_user(user) }
    elsif word == "Review Score"
      filtered = self.search(term).sort_by {|shop| shop.average_score.to_i }.reverse
    elsif word == "Popularity"
      filtered = self.search(term).sort_by {|shop| shop.popularity }.reverse
    end
    filtered
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shop, only: [:show, :edit, :update]
  
  

  def index
    redirect_to new_profile_path if current_user.profile.nil?
    
    # if params[:term]
    #   @shops = Shop.search(params[:term])
    if params[:filter].blank? && params[:term].blank?
      @shops = Shop.active_items
    elsif params[:filter] && params[:term].blank?
      @shops = Shop.filter_by(params[:filter], current_user)
    elsif params[:term] && params[:filter].blank?
      @shops = Shop.search(params[:term])
    elsif params[:term] && params[:filter]
      @shops = Shop.filter_search_by(params[:term], params[:filter], current_user)
    else
      @shops = Shop.active_items
    end
  end

  def show
    @items = Item.where(shop: @shop, active: true)
    @order = Order.new
  end

  def new
    # if user already has a profile, redirect them to the edit page if they manually type in '/myprofile/new'
    if current_user.shop
      redirect_to edit_shop_path(current_user.shop), notice: "Don't be greedy!"
    else
      @shop = Shop.new
    end
  end

  def edit
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.user = current_user

    if @shop.save
      redirect_to seller_profile_path, notice: 'Congratulations, start cooking!' 
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop Edited Succesfully' }
        format.json { render :show, status: :ok, location: shop_path }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end
  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(:filter, :shop_name, :shop_description, :shop_photo, :user_photo, :cuisine_type, :delivery_km, :delivery_cost,:shop_photo_data, :user_photo_data, :remove_shop_photo, :remove_user_photo, :term)
  end


end

app/helpers/shops_helper.rb
module ShopsHelper
  def to_stars(score)
    score_whole = score.to_i.floor
    remainder = score_whole - score.to_i
    erb = []
    score_whole.times do 
      erb << '<%= fa_icon "star" %>'
    end
    erb << '<%= fa_icon "star-half" %>' if remainder > 0.25
    erb.join('')
  end
end

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   
  <div class="field">
    <%= form.label 'Shop Name' %>
    <%= form.text_field :shop_name, id: :shop_shop_name %>
  </div>

  <div class="field">
    <%= form.label 'Description' %>
    <%= form.text_area :shop_description, id: :shop_shop_description, rows: "10" %>
  </div>

  <div class="field">
    <%= form.label :shop_photo %><br>
    <%= form.file_field :shop_photo, id: :shop_shop_photo %>
  </div>
  <div class="field">
      Remove attachment: <%= form.check_box :remove_shop_photo %>
  </div>

  <div class="field">
    <%= form.label :user_photo %><br>
    <%= form.file_field :user_photo, id: :shop_user_photo %>
  </div>
  <div class="field">
      Remove attachment: <%= form.check_box :remove_user_photo %>
  </div>
  
  <div class="field">
    <%= form.label :cuisine_type %>
    <%= form.select :cuisine_type, Shop::CUISINE_TYPES %>
  </div>

  <div>
    Please Ignore if Delivery is not offered
  </div>

  <div class="field">
    <%= form.label "Maximum Milage for Delivery (km)" %>
    <%= form.text_field :delivery_km, id: :shop_delivery_km %>
  </div>

  <div class="field">
    <%= form.label :delivery_cost %>
    <%= form.text_field :delivery_cost, id: :shop_delivery_cost %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', profile_path %>

app/views/shops/index.html.erb
<div class="container text-center my-3">
  <h3 class="heading-font txt-black">
    <%="Welcome #{current_user.profile.first_name.capitalize}!"%><br>
    <%= "Here are some home cooks around #{current_user.profile.suburb}" %>
  </h3>
  
</div>

<div class="container-fluid text-center">
  <%= form_with local: true, method: :get, url: shops_path do |form| %>
    <div class="row mt-2">
      <div class="col-12 col-lg-4 offset-lg-4">
        <%= form.text_field :term, class:"form-control w-100", placeholder: "Search for food, type, ingredients" %>
      </div>
    </div>
    <div class="row">
      <div class="col-12  mt-2">
        <span class="form-group mx-2">
          <%= form.select(:filter, Shop::FILTERS, {}, { :class => 'custom-select' }) %>
        </span>
      </div>
      <div class="col-12 mt-2">
        <span class="mx-2">
          <%= form.button :submit, class: "btn btn-primary" do %>
            <%= fa_icon "search", text: "Search" %>
          <% end %>
        </span>
      </div>
    </div>
  <% end %>
</div>

<div class="row mt-5 m-0 p-0">
  <% @shops.each do |shop| %>
    <div class="col-12 col-lg-4 mb-2">
      <div class="shop-lists">
        <%= link_to shop_path(shop) do %>
          <% if shop.shop_photo_data %>
            <%= image_tag shop.shop_photo_url(:large), class: "h-100" %>
          <% else %>
              <%= fa_icon "cutlery 5x", class: "txt-black navlink h-100" %>
          <% end %>
        <% end %>
      </div>
      <h6 class="text-black"><%= shop.shop_name %> 
        <span class="float-right">
          <% distance_from = shop.distance_from_user(current_user) %>
          <% if shop.owner == current_user %>
            <%= fa_icon "car" %>
            Your Shop
          <% elsif shop.delivery_km > distance_from %>
            <%= fa_icon "car" %>
            Delivery Avaliable
          <% else %>
            <%= fa_icon "pinterest-p" %>
            Pickup only
          <% end %>
        </span><br>
        <em class="float-right text-muted"><%= "#{shop.suburb}, #{distance_from}km " %></em>
        <em class="text-muted">
          <% score = shop.average_score %>
          <% score_whole = score.to_i.floor %>
          <% remainder = score.to_f - score_whole.to_f  %>
          <% score_whole.times do %>
            <%= fa_icon "star" %>
          <% end %>
          <% if remainder > 0.25 %>
            <%= fa_icon "star-half" %>
          <% end %>
        
        </em>
      </h6>
    </div>
  <% end %>
</div>

app/views/shops/new.html.erb
<h1>Become a Seller</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', profile_path %>

app/views/shops/show.html.erb
<div class="shop-banner">
  <% if @shop.shop_photo_data %>
    <%= image_tag @shop.shop_photo_url(:original), class: "w-100" %>
  <% else %>
    <img class="w-100" src="https://static.businessinsider.com/image/51f03f966bb3f73c7700000b/image.jpg" alt="poo">
  <% end %>
</div>
<div class="container bg-red py-2 w100">
  <div class="row">
    <div class="col-8 col-lg-10">
      <h2 class="shop-header"><%= @shop.shop_name %><small class="txt-grey"> by <%= @shop.owner.profile.first_name%></small></h2>
      <p class="body-font txt-grey">
        <span class="txt-grey">
          
          <% score = @shop.average_score %>
          <% score_whole = score.to_i.floor %>
          <% remainder = score.to_f - score_whole.to_f  %>
          <% score_whole.times do %>
            <%= fa_icon "star" %>
          <% end %>
          <% if remainder > 0.25 %>
            <%= fa_icon "star-half" %>
          <% end %>
        </span>
        <small><%= "Average Rating: #{score} from #{@shop.reviews.count} reviews" %></small>
      </p>
      <p class="txt-grey w-50"><%= @shop.shop_description %></p>
    </div>
    <div class="col-4 col-lg-2">
    
      <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @shop.user_id), class: "btn btn-secondary mt-2", method: 'post' do %>
        <%= fa_icon "envelope", text: "Message me!" %>
      <% end %>
      <%= link_to shop_reviews_path(@shop), class: "btn btn-secondary mt-1" do %>
        <%= fa_icon "bathtub", text: "See Reviews!" %>
      <% end %>
      <br><br>
      <span class="txt-white pt-2">
        <% if @shop.delivery_km > 0 %>
          <%= fa_icon "car", text: "Delivery within #{@shop.delivery_km}km" %>
        <% else %>
          <%= fa_icon "car", text: "Pickup only" %>
        <% end %>
      </span>
    </div>
  </div>
  <details class="bg-grey">
    <summary class="bg-red txt-white larger">About Seller</summary>
    <p>
      Hello, I am <%= @shop.owner.profile.first_name %>
    </p>
    <% if @shop.user_photo_data %>
      <%= image_tag @shop.user_photo_url(:thumb) %>
    <% end %>
  </details>
</div>
<div>
  <div class="container bg-grey text-center">
    <h4 class="heading-font txt-black py-4">Order Form</h4>
  </div>
<div>
  <%= form_with(model: @order, local: true) do |form| %>
    <%= form.hidden_field :buyer_id, :value => current_user.id %>
    <%= form.hidden_field :shop_id, :value => @shop.id %>
  
    <%= form.fields_for :order_items do |items_form| %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th class="col-8">Name & Details</th>
            <th class="col-2">Price</th>
            <th class="col-2">Quantity</th>
            
          </tr>
        </thead>
        <tbody>
          
          <% @items.each do |item| %>
            <tr>
              <td class="col-8">
                <details>
                  <summary>
                    <p><%= item.name %></p>
                  </summary>
                  <strong>Description:</strong>
                  <p><%= item.description %></p>
                  <strong>Allergies:</strong>
                  <p><%= item.allergies %></p>
                  <strong>Image:</strong>
                  <% if item.image_data %>
                    <%= image_tag item.image_url(:thumb) %>
                  <% else %>
                    <p>No Image</p>
                  <% end %>
                </details>
              </td>
              <td class="col-2">
                <p><%= "$#{item.price}0" %></p>
              </td>
              <td class="col-2">
                <%= items_form.fields_for "#{item.id}" do |item_form| %>
                  <%= item_form.text_field :quantity %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>  
    <% end %>
    
    <div class="row">
      <div class="col-4 col-lg-2 offset-8 offset-lg-10">
        
        <% if @shop.owner == current_user %>
          <%= link_to 'Back to Dashboard', seller_profile_path, class: "btn btn-primary" %>
        <% else %>
          <% if @shop.delivery_km > @shop.owner.profile.distance_between(current_user) %>
            <span>
              <%= form.check_box :delivery %>
            </span>
            <span>Delivery to:</span>
            <div class="float-right">
              <%= current_user.profile.full_street_address %>
              <p><%= " + $#{@shop.delivery_cost}.00" %></p>
            </div>
          <% else %>
            <div>
              <%= "You are not in #{@shop.owner.profile.first_name.capitalize}'s Delivery Zone" %><br>
              <%= "Pickup from #{@shop.suburb} only." %>
            </div>
          <% end %>
          <div class="">
            <%= form.submit "Order", class: "btn btn-primary p-3 float-right mt-3"%>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>