config/routes.rb
Rails.application.routes.draw do
  
  post 'order_items/create', to:'order_items#create', as: 'order_items'
  # Orders
  resources :orders, only: [:create, :show, :new, :update] do
    get '/payment', to: 'charges#new', as: 'new_charge'
    resources :charges, only: [:create]
    resources :reviews, only: [:new, :create]
  end
  devise_for :users

  # Landing s and dashboards
  root 'landing#index', as: 'home'
  get '/shopdashboard', to: 'seller_profiles#index', as: 'seller_profile'
  get '/dashboard/', to: 'dashboard#index', as: 'dashboard' 
  
  # Routes for profile
  post '/profiles', to: 'profiles#create', as: 'profiles'
  get '/profile/new', to: 'profiles#new', as: 'new_profile'
  get '/profile/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profile', to: 'profiles#update'
  put '/profile', to: 'profiles#update'
  # resources :profiles, only: [:new, :edit, :create, :update]
  
  # Routes for seller profile
  
  # Routes for shop
  resources :shops do
    get '/reviews', to: 'reviews#index', as: 'reviews'
    get '/orders', to: 'orders#index', as: 'orders'
  end
  # Routes for items
  resources :items, only: [:new, :create, :update, :edit, :destroy] 
  
  # Routes for conversations
  resources :conversations do
    resources :messages
  end
end

app/models/seller_profile.rb
class SellerProfile < ApplicationRecord
  include ShopPhotoUploader[:shop_photo]
  include UserPhotoUploader[:user_photo]
  belongs_to :user
  has_many :item
  validates_presence_of :shop_name, :cuisine_type
  validates :delivery_cost, numericality: { greater_than_or_equal_to: 0, less_than: 20 }
  
  CUISINE_TYPES = ["Continental", "Chinese", "French", "Italian", "Japanese", "Mexican", "Spanish", "Ethiopian", "Thai", "African", "Vietnamese"]
end

app/controllers/seller_profiles_controller.rb
class SellerProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shop 
  
  def index
    @items = Item.where(shop: @shop)
    @orders = Order.where(shop: @shop).where.not(charge_identifier: nil).where.not("mark_as_done = ? AND delivered = ?", true, true).order(created_at: :desc)
  end
    
  def show
  end

  def new
    # if user already has a profile, redirect them to the edit page if they manually type in '/myprofile/new'
    if current_user.shop
      redirect_to edit_shop_path
    else
      @shop = Shop.new
    end
  end

  def edit
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.user = current_user

    if @shop.save
      redirect_to seller_profile_path, notice: 'Congratulations, start cooking!' 
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to seller_profile_path, notice: 'Congratulations, you are now a certified chef!' }
        format.json { render :show, status: :ok, location: shop_path }
      else
        format.html { redirect_to edit_seller_profile }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end
  private

  def set_shop
    @shop = current_user.shop
    
  end

  def shop_params
    params.require(:shop).permit(:shop_name, :shop_description, :shop_photo, :user_photo, :cuisine_type, :delivery_km, :delivery_cost,:shop_photo_data, :user_photo_data, :remove_shop_photo, :remove_user_photo)
  end
  

end

app/helpers/seller_profiles_helper.rb
module SellerProfilesHelper
end

app/views/seller_profiles/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form', seller_profile: @seller_profile %>

<%= link_to 'Back', profile_path %>

app/views/seller_profiles/index.html.erb
<div class="container bg-blue text-center">
  <h1 class="heading-font txt-white pt-3">My Shop Dashboard</h1>
  <h3 class="heading-font txt-white pb-3"><%= @shop.shop_name %></h3>
  <div class="row">
    <span class="col-12 col-lg-12">
      <h5 class="heading-font txt-grey pb-3"><%= "#{@shop.owner.profile.first_name}, #{@shop.owner.email}" %></h5>
    </span>
    <div class="col-12">
      <h5 class="body-font txt-grey">
        <span class="txt-grey">
          
          <% score = @shop.average_score %>
          <% score_whole = score.to_i.floor %>
          <% remainder = score.to_f - score_whole.to_f  %>
          <% score_whole.times do %>
            <%= fa_icon "star" %>
          <% end %>
          <% if remainder > 0.25 %>
            <%= fa_icon "star-half" %>
          <% end %>
        </span>
        <small><%= "Average Rating: #{score} from #{@shop.reviews.count} reviews" %></small>
      </h5>
    </div>
    <span class="col-12 col-lg-12">
      <%= link_to edit_profile_path, class: "btn btn-red mb-4" do %>
        <%= fa_icon "pencil", text: "Edit My Details" %>
      <% end %>
      <%= link_to @shop, class: "btn btn-red mb-4" do %>
        <%= fa_icon "shopping-bag", text: "My Shop" %>
      <% end %>
      <%= link_to shop_reviews_path(@shop), class: "btn btn-red mb-4" do %>
        <%= fa_icon "bathtub", text: "My Reviews" %>
      <% end %>
    </span>
  </div>
</div>

<div class="row">
  <div class="col-12 col-lg-12 mb-3">
    <div class="container bg-grey text-center">
      <h4 class="heading-font txt-black py-4">My Active Orders</h4>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Items</th>
          <th>Delivery</th>
          <th>Price</th>
          <th>Order</th>
          <th>Mark as done</th>
          <th>Mark as Delivered/<br>
          Picked up</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td>
              <%= order.date %><br>
              <%= order.time %>
            </td>
            <td>
              <% order.order_items.each do |order_item| %>
                <%= order_item.quantity %> x <%= order_item.name %><br>
              <% end %>
            </td>
            <td><%= order.delivery_address %></td>
            <td>$<%= order.subtotal %>0</td>
            <td>
              <%= link_to order_path(order), class: "btn btn-red" do %>
                <%= fa_icon "file-text-o" %>
              <% end %>
            </td>
            <td>
              <% if order.done? %>
                <%= form_for order do |f| %>
                  <%= f.hidden_field :mark_as_done, value: false %>
                  <%= f.button :submit, class: "btn btn-primary" do %>
                    <%= fa_icon "square" %>
                  <% end %>
                <% end %>
              <% else %>
                <%= form_for order do |f| %>
                  <%= f.hidden_field :mark_as_done, value: true %>
                  <%= f.button :submit, class: "btn btn-red" do %>
                    <%= fa_icon "check-square" %>
                  <% end %>
                <% end %>
              <% end %>
            </td>
            <td>
              <% if order.delivered %>
                <%= form_for order do |f| %>
                  <%= f.hidden_field :delivered, value: false %>
                  <%= f.button :submit, class: "btn btn-primary" do %>
                    <%= fa_icon "check-square" %>
                  <% end %>
                <% end %>
              <% else %>
                <%= form_for order do |f| %>
                  <%= f.hidden_field :delivered, value: true %>
                  <%= f.button :submit, class: "btn btn-red" do %>
                    <%= fa_icon "car" %>
                  <% end %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="container bg-grey text-center py-3">
      <%= link_to "View All", shop_orders_path(@shop), class: "btn btn-primary" %>
    </div>
  </div>

  <div class="col-12 col-lg-6">
    <div class="container bg-grey text-center">
      <h4 class="heading-font txt-black py-4">Shop Details</h4>
    </div>
    <table class="table">
      <tr>
        <th scope="row">Name:</th>
        <td><%= @shop.shop_name %></td>
      </tr>
      <tr>
        <th scope="row">Description:</th>
        <td><%= @shop.shop_description %></td>
      </tr>
      <tr>
        <th scope="row">Cuisine</th>
        <td><%= @shop.cuisine_type %></td>
      </tr>
      <tr>
        <th scope="row">Delivery</th>
        <td>
          <% if @shop.delivery_km.to_i > 0 %>
            <p>Yes, within <strong><%= @shop.delivery_km %>km</strong> of:</p>
            <p><%= @shop.street_address %>,<br>
            <%= @shop.suburb %>, <%= @shop.state %></p>
          <% else %>
            <p>Pickup from:</p>
            <p><%= @shop.street_address %>,<br>
            <%= @shop.suburb %>, <%= @shop.state %></p>
          <% end %>
        </td>
      </tr>
      <tr>
        <th scope="row">Shop Photo</th>
        <td>
          <% if @shop.shop_photo_data %>
            <%= image_tag @shop.shop_photo_url(:thumb) %>
          <% else %>
            <p>No Image</p>
          <% end %>
        </td>
      </tr>
      <tr>
        <th scope="row">Your Photo</th>
        <td>
          <% if @shop.user_photo_data %>
            <%= image_tag @shop.user_photo_url(:thumb) %>
          <% else %>
            <p>No Image</p>
          <% end %>
        </td>
      </tr>
    </table>

    <div class="container bg-grey text-center py-3">
      <%= link_to "Edit Shop", edit_shop_path(@shop), class: "btn btn-primary mx-1" %>
      <%= link_to "Go to Shop", shop_path(@shop), class: "btn btn-red mx-1" %>
    </div>
  </div>

  <div class="col-12 col-lg-6 float-left">
    <div class="container bg-grey text-center">
      <h4 class="heading-font txt-black py-4">My Items</h4>
    </div>
    <div class="bg-white">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name & Details</th>
            <th>Price</th>
            <th>Activate</th>
            <th>Edit/Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td class="col-6 col-lg-6">
                <details class="details-width">
                  <summary>
                    <strong><%= item.name %></strong>
                    <span class="float-right">
                      <% fa_icon "leaf" if item.vegetarian %>
                    </span>
                  </summary>
                  <strong>Description:</strong>
                  <p><%= item.description %></p>
                  <strong>Allergies:</strong>
                  <p><%= item.allergies %></p>
                  <strong>Image:</strong>
                  <% if item.image_data %>
                    <%= image_tag item.image_url(:thumb) %>
                  <% else %>
                    <p>No Image</p>
                  <% end %>
                </details>
              </td>
              <td><%= "$#{item.price}0" %>
              <td>
                <% if item.active? %>
                  <%= form_for item do |f| %>
                    <%= f.hidden_field :active, value: false %>
                    <%= f.button :submit, class: "btn btn-red" do %>
                      <%= fa_icon "stop", text: "De-activate" %>
                    <% end %>
                  <% end %>
                <% else %>
                  <%= form_for item do |f| %>
                    <%= f.hidden_field :active, value: true %>
                    <%= f.button :submit, class: "btn btn-primary" do %>
                      <%= fa_icon "play", text: "Activate" %>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to edit_item_path(item), class: "btn btn-primary" do %>
                  <%= fa_icon "pencil" %>
                <% end %>
                <%= link_to seller_profile_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-red" do %>
                  <%= fa_icon "times" %>
                <% end %>

              </td>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="container bg-grey text-center p-3">
      <%= link_to "Add New Item", new_item_path, class: "btn btn-primary" %> 
    </div>
  </div>