config/routes.rb
Rails.application.routes.draw do
  
  post 'order_items/create', to:'order_items#create', as: 'order_items'
  # Orders
  resources :orders, only: [:create, :show, :new, :update] do
    get '/payment', to: 'charges#new', as: 'new_charge'
    resources :charges, only: [:create]
    resources :reviews, only: [:new, :create]
  end
  devise_for :users

  # Landing s and dashboards
  root 'landing#index', as: 'home'
  get '/shopdashboard', to: 'seller_profiles#index', as: 'seller_profile'
  get '/dashboard/', to: 'dashboard#index', as: 'dashboard' 
  
  # Routes for profile
  post '/profiles', to: 'profiles#create', as: 'profiles'
  get '/profile/new', to: 'profiles#new', as: 'new_profile'
  get '/profile/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profile', to: 'profiles#update'
  put '/profile', to: 'profiles#update'
  # resources :profiles, only: [:new, :edit, :create, :update]
  
  # Routes for seller profile
  
  # Routes for shop
  resources :shops do
    get '/reviews', to: 'reviews#index', as: 'reviews'
    get '/orders', to: 'orders#index', as: 'orders'
  end
  # Routes for items
  resources :items, only: [:new, :create, :update, :edit, :destroy] 
  
  # Routes for conversations
  resources :conversations do
    resources :messages
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order
  
  def new
  end
    
  def create
    # Amount in cents
    @amount = (@order.total_price * 100).to_i
    customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'aud'
    )
    
    @order.charge_identifier = charge.id
    @order.save
    redirect_to order_path(@order) if @order.save

    rescue Stripe::CardError => e
        flash[:error] = e.message
    
  end

  private
  def set_order
    @order = Order.find(params[:order_id])
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/new.html.erb
<div class="container bg-red text-center">
  <h4 class="heading-font txt-white py-4">Order #000<%= @order.id%></h4>
  <p id="notice"><small><%= notice %></small></p>
</div>


<table class="table">
  <tbody>
  <tr>
    <th class="w-25" scope="row">Date</th>
    <td ><%= @order.date %></td>
  </tr>
  <tr>
    <th scope="row">Time</th>
    <td><%= @order.time %></td>
  </tr>
  <tr>
    <th scope="row">Seller</th>
    <td>
      <%= @order.shop.shop_name %><br>
      <%= @order.shop.owner.email %><br>
      <%= @order.shop.owner.profile.first_name %> 
      <%= @order.shop.owner.profile.last_name %>
    </td>
  </tr>
  <tr>
    <th scope="row">Buyer</th>
    <td>
      <%= @order.buyer.email %><br>
      <%= @order.buyer.profile.first_name %>
      <%= @order.buyer.profile.last_name %>      
    </td>
  </tr>
  </tbody>
</table>
<table class="table">
  <thead class="bg-grey">
    <tr>
      <td>Item Name:</td>
      <td>Quantity:</td>
      <td>Price:</td>
      <td>Subtotal</td>
    </tr>
  </thead>
  <tbody>
    <% @order.order_items.each do |order_item|%>
      <tr>
        <td><%= order_item.item.name %></td>
        <td><%= order_item.quantity %></td>
        <td><%= "$#{order_item.item.price}0" %></td>
        <td><%= "$#{order_item.quantity * order_item.item.price}0" %></td>
      </tr>
    <% end %>
    <tr>
      <td>
        <strong>Shipping: </strong>
        <br>
        <%= @order.delivery_address %>
      </td>
      <td></td>
      <td></td>
      <td><%= "$#{@order.delivery_price}.00" %></td>
    </tr>
    <tr>
      <td>
        <strong>Grand total:</strong>
      </td>
      <td></td>
      <td></td>
      <td><strong><%= "$#{@order.subtotal}0" %></strong></td>
    </tr>
  </tbody>
</table>
<div class="text-center">
  <%= form_tag order_charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Amount: <%= "$#{@order.total_price}0" %></span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="<%= "Order from #{@order.shop.shop_name}" %>"
            data-email= <%= current_user.email %>
            data-amount="<%= (@order.total_price * 100).to_i %>"
            data-currency="aud">
            </script>
  <% end %>
</div>